data:
  file_path: "../data/MLE-Assignment.csv"
  processed_path: "../data/processed_data.csv"

preprocessing:
  missing_value_strategy: "median"
  normalization: "StandardScaler"
  anomaly_detection: "IQR"

training:
  model: "NeuralNetwork"
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  optimizer: "Adam"
  loss_function: "MSELoss"
  train_split: 0.8
  test_split: 0.2

deployment:
  api_host: "0.0.0.0"
  api_port: 8000
